[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm ci && npm run build && cp -r dist/* ../backend/static/"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"